export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS'
export const FETCH_TRANSACTIONS_REJECTED = 'FETCH_TRANSACTIONS_REJECTED'
export const FETCH_TRANSACTIONS_FULFILLED = 'FETCH_TRANSACTIONS_FULFILLED'